PLUGINOBJECTS = Merge.o
PLUGINNAME = Merge
RESOURCES = net.sf.openfx.MergePlugin.png net.sf.openfx.MergePlugin.svg net.sf.openfx.MergeDifference.png net.sf.openfx.MergeIn.png net.sf.openfx.MergeMax.png net.sf.openfx.MergeMin.png net.sf.openfx.MergeMultiply.png net.sf.openfx.MergeOut.png net.sf.openfx.MergePlus.png net.sf.openfx.MergeScreen.png

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
