PLUGINOBJECTS = JoinViews.o PluginRegistration.o
PLUGINNAME = JoinViews
RESOURCES = net.sf.openfx.joinViewsPlugin.png net.sf.openfx.joinViewsPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

