PLUGINOBJECTS = \
Anaglyph.o \
ChromaKeyer.o \
ColorCorrect.o \
CornerPin.o \
Crop.o \
Grade.o \
JoinViews.o \
Merge.o \
MixViews.o \
OneView.o \
RGBLut.o \
Roto.o \
SideBySide.o \
Switch.o \
TimeOffset.o \
Transform.o \
ofxsOGLTextRenderer.o \
ofxsOGLFontData.o  \
ofxsTransform3x3.o \
PluginRegistrationCombined.o

PLUGINNAME = Misc
VPATH += \
../Anaglyph \
../ChromaKeyer \
../ColorCorrect \
../CornerPin \
../Crop \
../Grade \
../JoinViews \
../Merge \
../MixViews \
../OneView \
../RGBLut \
../Roto \
../SideBySide \
../Switch \
../TimeOffset \
../Transform

include ../Makefile.master

CXXFLAGS += \
-I. \
-I../Anaglyph \
-I../ChromaKeyer \
-I../ColorCorrect \
-I../CornerPin \
-I../Crop \
-I../Grade \
-I../JoinViews \
-I../Merge \
-I../MixViews \
-I../OneView \
-I../RGBLut \
-I../Roto \
-I../SideBySide \
-I../Switch \
-I../TimeOffset \
-I../Transform
