PLUGINOBJECTS = \
        Switch.o \
        TimeOffset.o \
        RGBLut.o \
        SideBySide.o \
        MixViews.o \
        OneView.o \
        JoinsViews.o \
        Anaglyph.o \
        PluginRegistrationCombined.o

PLUGINNAME = Misc
VPATH += ../Switch ../TimeOffset ../RGBLut ../SideBySide ../MixViews ../OneView ../JoinViews ../Anaglyph

include ../Makefile.master

