PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ColorTransform.o ofxsLut.o
PLUGINNAME = ColorTransform
RESOURCES = \
net.sf.openfx.HSVToRGB.png \
net.sf.openfx.HSVToRGB.svg \
net.sf.openfx.LabToRGB709.png \
net.sf.openfx.RGBToHSV.png \
net.sf.openfx.RGBToHSV.svg \
net.sf.openfx.RGB709ToLab.png \
net.sf.openfx.RGB709ToLab.svg \
net.sf.openfx.RGB709ToXYZ.png \
net.sf.openfx.RGB709ToXYZ.svg \
net.sf.openfx.XYZToRGB709.png \
net.sf.openfx.XYZToRGB709.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
