PLUGINOBJECTS = ColorTransform.o ofxsLut.o
PLUGINNAME = ColorTransform
RESOURCES = \
net.sf.openfx.HSVToRGB.png \
net.sf.openfx.HSVToRGB.svg \
net.sf.openfx.LABToRGB.png \
net.sf.openfx.RGBToHSV.png \
net.sf.openfx.RGBToHSV.svg \
net.sf.openfx.RGBToLAB.png \
net.sf.openfx.RGBToLAB.svg \
net.sf.openfx.RGBToXYZ.png \
net.sf.openfx.RGBToXYZ.svg \
net.sf.openfx.XYZToRGB.png \
net.sf.openfx.XYZToRGB.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
