PLUGINOBJECTS = ColorTransform.o ofxsLut.o
PLUGINNAME = ColorTransform
RESOURCES = \
net.sf.openfx.RGBToHSVPlugin.png \
net.sf.openfx.HSVToRGBPlugin.png \
net.sf.openfx.RGBToHSVPlugin.svg \
net.sf.openfx.HSVToRGBPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
