PLUGINOBJECTS = HSV.o ofxsLut.o PluginRegistration.o
PLUGINNAME = HSV
RESOURCES = net.sf.openfx.RGBToHSVPlugin.png \
net.sf.openfx.HSVToRGBPlugin.png \
net.sf.openfx.RGBToHSVPlugin.svg \
net.sf.openfx.HSVToRGBPlugin.svg

include ../Makefile.master
