PLUGINOBJECTS = Difference.o PluginRegistration.o
PLUGINNAME = Difference
RESOURCES = net.sf.openfx.DifferencePlugin.png net.sf.openfx.DifferencePlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
