PLUGINOBJECTS = PIK.o ofxsLut.o
PLUGINNAME = PIK
#RESOURCES = net.sf.openfx.PIK.png net.sf.openfx.PIK.svg
RESOURCES = PIKColor.py PIKColor.gizmo

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
