PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o PIK.o ofxsLut.o
PLUGINNAME = PIK
RESOURCES = net.sf.openfx.PIK.png net.sf.openfx.PIK.svg fr.inria.PIKColor.png fr.inria.PIKColor.svg PIKColor.gizmo PIKColor.py
RESOURCES = PIKColor.py PIKColor.gizmo

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
