PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o Radial.o ofxsGenerator.o ofxsRectangleInteract.o
PLUGINNAME = Radial
RESOURCES = net.sf.openfx.Radial.png net.sf.openfx.Radial.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
