PATHTOROOT = ../openfx/Support

include $(PATHTOROOT)/Plugins/Makefile.master

CXXFLAGS += -DOFX_EXTENSIONS_VEGAS -DOFX_EXTENSIONS_NUKE

CXXFLAGS += -I../Misc -I../SupportExt
VPATH += ../Misc ../SupportExt
