PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ofxsTransform3x3.o ofxsTransformInteract.o ofxsShutter.o GodRays.o
PLUGINNAME = GodRays
RESOURCES = net.sf.openfx.GodRays.png net.sf.openfx.GodRays.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
