PLUGINOBJECTS = GodRays.o PluginRegistration.o ofxsTransform3x3.o ofxsTransformInteract.o
PLUGINNAME = GodRays
#RESOURCES = net.sf.openfx.GodRaysPlugin.png net.sf.openfx.GodRaysPlugin.svg

include ../Makefile.master
