PLUGINOBJECTS = GodRays.o PluginRegistration.o ofxsTransform3x3.o ofxsTransformInteract.o ofxsShutter.o
PLUGINNAME = GodRays
RESOURCES = net.sf.openfx.GodRays.png net.sf.openfx.GodRays.svg

include ../Makefile.master
