PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o DenoiseSharpen.o ofxsLut.o ofxsRectangleInteract.o
PLUGINNAME = DenoiseSharpen
#RESOURCES = net.sf.openfx.DenoiseSharpen.png net.sf.openfx.DenoiseSharpen.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
