PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ColorCorrect.o
PLUGINNAME = ColorCorrect
RESOURCES = net.sf.openfx.ColorCorrectPlugin.png net.sf.openfx.ColorCorrectPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
