PLUGINOBJECTS = Dissolve.o PluginRegistration.o
PLUGINNAME = Dissolve
RESOURCES = net.sf.openfx.DissolvePlugin.png net.sf.openfx.DissolvePlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
