PLUGINOBJECTS = Distort.o PluginRegistration.o ofxsTransform3x3.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = Distortion
#RESOURCES = net.sf.openfx.IDistort.png net.sf.openfx.IDistort.svg net.sf.openfx.STMap.png net.sf.openfx.STMap.svg

include ../Makefile.master
