PLUGINOBJECTS = Distortion.o PluginRegistration.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = Distortion
RESOURCES = net.sf.openfx.IDistort.png net.sf.openfx.IDistort.svg net.sf.openfx.STMap.png net.sf.openfx.STMap.svg net.sf.openfx.LensDistortion.png net.sf.openfx.LensDistortion.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
