PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o HueCorrect.o HueCorrect1.o ofxsLut.o
PLUGINNAME = HueCorrect
RESOURCES = \
net.sf.openfx.HueCorrect.png \
net.sf.openfx.HueCorrect.svg \
net.sf.openfx.HueKeyer.png \
net.sf.openfx.HueKeyer.svg \

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
