PLUGINOBJECTS = HSVTool.o ofxsLut.o PluginRegistration.o
PLUGINNAME = HSVTool
RESOURCES = net.sf.openfx.HSVToolPlugin.png net.sf.openfx.HSVToolPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
