PLUGINOBJECTS = Rectangle.o PluginRegistration.o ofxsGenerator.o ofxsRectangleInteract.o
PLUGINNAME = Rectangle.o
RESOURCES = net.sf.openfx.Rectangle.png net.sf.openfx.Rectangle.svg

include ../Makefile.master
