PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o Rectangle.o ofxsGenerator.o ofxsRectangleInteract.o
PLUGINNAME = Rectangle
RESOURCES = net.sf.openfx.Rectangle.png net.sf.openfx.Rectangle.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
