PLUGINOBJECTS = Crop.o ofxsRectangleInteract.o ofxsGenerator.o
PLUGINNAME = Crop
RESOURCES = net.sf.openfx.CropPlugin.png net.sf.openfx.CropPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
