PLUGINOBJECTS = Ramp.o ofxsOGLTextRenderer.o ofxsOGLFontData.o ofxsRamp.o
PLUGINNAME = Ramp
RESOURCES = net.sf.openfx.Ramp.png net.sf.openfx.Ramp.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
