PLUGINOBJECTS = TimeBlur.o NoTimeBlur.o PluginRegistration.o ofxsShutter.o
PLUGINNAME = TimeBlur
RESOURCES = net.sf.openfx.TimeBlur.png net.sf.openfx.TimeBlur.svg net.sf.openfx.NoTimeBlur.png net.sf.openfx.NoTimeBlur.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

