PLUGINOBJECTS = CheckerBoard.o ofxsRectangleInteract.o PluginRegistration.o
PLUGINNAME = CheckerBoard
#RESOURCES = net.sf.openfx.CheckerBoardPlugin.png net.sf.openfx.CheckerBoardPlugin.svg

include ../Makefile.master
