PLUGINOBJECTS = \
	Shadertoy.o ShadertoyRenderGL.o  ShadertoyRenderMesa.o

PLUGINNAME = Shadertoy

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

## Enable these if you installed a mangled OSMesa (preferably with 32 bits FP support)
#CXXFLAGS += -DHAVE_OSMESA -I$(OSMESA_PATH)/include
#LINKFLAGS += -L$(OSMESA_PATH)/lib -l
