PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o MixViews.o
PLUGINNAME = MixViews
RESOURCES = net.sf.openfx.mixViewsPlugin.png net.sf.openfx.mixViewsPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

