PLUGINOBJECTS = ChromaKeyer.o PluginRegistration.o
PLUGINNAME = ChromaKeyer
RESOURCES = net.sf.openfx.ChromaKeyerPlugin.png net.sf.openfx.ChromaKeyerPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
