PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o FrameRange.o
PLUGINNAME = FrameRange
RESOURCES = net.sf.openfx.FrameRange.png net.sf.openfx.FrameRange.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

