PLUGINOBJECTS = ChannelMath.o PluginRegistration.o
PLUGINNAME = ChannelMath
RESOURCES = com.casanico.ChannelMath.png com.casanico.ChannelMath.svg GNU-GPL-3.0.txt README.txt

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

