PLUGINOBJECTS = CopyRectangle.o ofxsRectangleInteract.o PluginRegistration.o
PLUGINNAME = CopyRectangle
#RESOURCES = net.sf.openfx.CopyRectanglePlugin.png net.sf.openfx.CopyRectanglePlugin.svg
include ../Makefile.master
