PLUGINOBJECTS = CopyRectangle.o ofxsRectangleInteract.o
PLUGINNAME = CopyRectangle
#RESOURCES = net.sf.openfx.CopyRectanglePlugin.png net.sf.openfx.CopyRectanglePlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
