PLUGINOBJECTS = Reformat.o PluginRegistration.o ofxsTransform3x3.o ofxsTransformInteract.o ofxsShutter.o
PLUGINNAME = Reformat
RESOURCES = net.sf.openfx.Reformat.png net.sf.openfx.Reformat.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
