PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o Keyer.o
PLUGINNAME = Keyer
RESOURCES = net.sf.openfx.KeyerPlugin.png net.sf.openfx.KeyerPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
