PLUGINOBJECTS = VectorToColor.o ofxsLut.o PluginRegistration.o
PLUGINNAME = VectorToColor
RESOURCES = net.sf.openfx.VectorToColorPlugin.png net.sf.openfx.VectorToColorPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
