PLUGINOBJECTS = \
    bl_defocus_plugin.o \
	bl_defocus_processor.o \
	bl_zdefocus_plugin.o \
	CMP_defocus.o \
	BLI_rand.o \
	ImathRandom.o \
	register_plugins.o

PLUGINNAME = Bl_Defocus

include ../Makefile.master
