PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o FrameHold.o
PLUGINNAME = FrameHold
RESOURCES = net.sf.openfx.FrameHold.png net.sf.openfx.FrameHold.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

