PLUGINOBJECTS = ofxsThreadSuite.o ofxsMultiPlane.o tinythread.o Premult.o
PLUGINNAME = Premult
RESOURCES = net.sf.openfx.Premult.png  net.sf.openfx.Premult.svg net.sf.openfx.Unpremult.png net.sf.openfx.Unpremult.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
