PLUGINOBJECTS = Premult.o PluginRegistration.o
PLUGINNAME = Premult
RESOURCES = net.sf.openfx.Premult.png  net.sf.openfx.Premult.svg net.sf.openfx.Unpremult.png net.sf.openfx.Unpremult.svg

include ../Makefile.master
