PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o Deinterlace.o
PLUGINNAME = Deinterlace
RESOURCES = net.sf.openfx.Deinterlace.png net.sf.openfx.Deinterlace.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
