PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ColorSuppress.o
PLUGINNAME = ColorSuppress
#RESOURCES = net.sf.openfx.ColorSuppress.png net.sf.openfx.ColorSuppress.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
