PLUGINOBJECTS = Constant.o ofxsRectangleInteract.o ofxsGenerator.o
PLUGINNAME = Constant
RESOURCES = net.sf.openfx.ConstantPlugin.png net.sf.openfx.ConstantPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
