PLUGINOBJECTS = Constant.o ofxsRectangleInteract.o ofxsGenerator.o PluginRegistration.o
PLUGINNAME = Constant
RESOURCES = net.sf.openfx.ConstantPlugin.png net.sf.openfx.ConstantPlugin.svg

include ../Makefile.master
