PLUGINOBJECTS = NoOp.o ofxsGenerator.o ofxsRectangleInteract.o
PLUGINNAME = NoOp
RESOURCES = net.sf.openfx.NoOpPlugin.png net.sf.openfx.NoOpPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

