PLUGINOBJECTS = ofxsThreadSuite.o ofxsMultiPlane.o tinythread.o MaskableFilter.o MixableFilter.o SimpleFilter.o
PLUGINNAME = Templates
#RESOURCES = net.sf.openfx.MaskableFilter.png net.sf.openfx.MaskableFilter.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
