PLUGINOBJECTS = IDistort.o PluginRegistration.o ofxsTransform3x3.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = IDistort
#RESOURCES = net.sf.openfx.IDistort.png net.sf.openfx.IDistort.svg

include ../Makefile.master
