PLUGINOBJECTS = Transform.o PluginRegistration.o ofxsTransform3x3.o ofxsTransformInteract.o
PLUGINNAME = Transform
RESOURCES = net.sf.openfx.TransformMaskedPlugin.png net.sf.openfx.TransformPlugin.png net.sf.openfx.TransformMaskedPlugin.svg net.sf.openfx.TransformPlugin.svg net.sf.openfx.DirBlur.png net.sf.openfx.DirBlur.svg

include ../Makefile.master
