PLUGINOBJECTS = Transform.o PluginRegistration.o ofxsTransform3x3.o ofxsTransformInteract.o ofxsShutter.o
PLUGINNAME = Transform
RESOURCES = net.sf.openfx.TransformMaskedPlugin.png net.sf.openfx.TransformPlugin.png net.sf.openfx.TransformMaskedPlugin.svg net.sf.openfx.TransformPlugin.svg net.sf.openfx.DirBlur.png net.sf.openfx.DirBlur.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
