PLUGINOBJECTS = Transform.o PluginRegistration.o ofxsTransform3x3.o
PLUGINNAME = Transform
RESOURCES = net.sf.openfx.TransformMaskedPlugin.png net.sf.openfx.TransformPlugin.png

include ../Makefile.master
