PLUGINOBJECTS = ImageStatistics.o PluginRegistration.o ofxsLut.o ofxsRectangleInteract.o
PLUGINNAME = ImageStatistics.o
#RESOURCES = net.sf.openfx.ImageStatistics.png net.sf.openfx.ImageStatistics.svg

include ../Makefile.master
