PLUGINOBJECTS = ImageStatistics.o PluginRegistration.o ofxsLut.o ofxsRectangleInteract.o
PLUGINNAME = ImageStatistics
RESOURCES = net.sf.openfx.ImageStatistics.png net.sf.openfx.ImageStatistics.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
