PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o TimeBuffer.o
PLUGINNAME = TimeBuffer
#RESOURCES = net.sf.openfx.TimeBufferRead.png net.sf.openfx.TimeBufferRead.svg net.sf.openfx.TimeBufferWrite.png net.sf.openfx.TimeBufferWrite.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
