PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ColorWheel.o ofxsRectangleInteract.o ofxsGenerator.o ofxsLut.o
PLUGINNAME = ColorWheel
RESOURCES = net.sf.openfx.ColorWheel.png net.sf.openfx.ColorWheel.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
