PLUGINOBJECTS = ColorWheel.o ofxsRectangleInteract.o ofxsGenerator.o
PLUGINNAME = ColorWheel
#RESOURCES = net.sf.openfx.ColorWheel.png net.sf.openfx.ColorWheel.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
