PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o SpriteSheet.o ofxsRectangleInteract.o ofxsGenerator.o
PLUGINNAME = SpriteSheet
#RESOURCES = net.sf.openfx.SpriteSheetPlugin.png net.sf.openfx.SpriteSheetPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
