PLUGINOBJECTS = LayerContactSheet.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = LayerContactSheet
#RESOURCES = net.sf.openfx.switchPlugin.png net.sf.openfx.switchPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

