PLUGINOBJECTS = CornerPin.o PluginRegistration.o ofxsTransform3x3.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = CornerPin
RESOURCES = net.sf.openfx.CornerPinMaskedPlugin.png net.sf.openfx.CornerPinPlugin.png net.sf.openfx.CornerPinMaskedPlugin.svg net.sf.openfx.CornerPinPlugin.svg

include ../Makefile.master
