PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o ofxsTransform3x3.o ofxsOGLTextRenderer.o ofxsOGLFontData.o ofxsShutter.o CornerPin.o
PLUGINNAME = CornerPin
RESOURCES = net.sf.openfx.CornerPinMaskedPlugin.png net.sf.openfx.CornerPinPlugin.png net.sf.openfx.CornerPinMaskedPlugin.svg net.sf.openfx.CornerPinPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
