PLUGINOBJECTS = TrackerPM.o ofxsTracking.o ofxsOGLFontData.o ofxsOGLTextRenderer.o PluginRegistration.o
PLUGINNAME = TrackerPM
RESOURCES = net.sf.openfx.TrackerPM.png net.sf.openfx.TrackerPM.svg

include ../Makefile.master
