PLUGINOBJECTS = TrackerPM.o ofxsTracking.o ofxsOGLFontData.o ofxsOGLTextRenderer.o PluginRegistration.o
PLUGINNAME = TrackerPM
RESOURCES = net.sf.openfx.TrackerPM.png net.sf.openfx.TrackerPM.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
