PLUGINOBJECTS = ColorLookup.o PluginRegistration.o
PLUGINNAME = ColorLookup
RESOURCES = net.sf.openfx.ColorLookupPlugin.png net.sf.openfx.ColorLookupPlugin.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
