PLUGINOBJECTS = Position.o PluginRegistration.o ofxsOGLTextRenderer.o ofxsOGLFontData.o
PLUGINNAME = Position
RESOURCES = net.sf.openfx.Position.png net.sf.openfx.Position.svg

include ../Makefile.master
