PLUGINOBJECTS = DebugProxy.o ofxhBinary.o
PLUGINNAME = DebugProxy
PATHTOROOT = ../openfx/Examples

VPATH=$(PATHTOROOT)/../HostSupport/src

include $(PATHTOROOT)/Makefile.master

CXXFLAGS += -I$(PATHTOROOT)/../HostSupport/include
