PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o FrameBlend.o
PLUGINNAME = FrameBlend
RESOURCES = net.sf.openfx.FrameBlend.png net.sf.openfx.FrameBlend.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

